#Build out jar
FROM maven:3.9.11-eclipse-temurin-25
WORKDIR /app
COPY src /src
COPY pom.xml .
RUN mvn clean package -DskipTests

#Run jar
FROM eclipse-temurin:25-jdk
WORKDIR /app
ADD target/NFL-PlayerStats.jar NFL-PlayerStats.jar
ENTRYPOINT ["java","-jar","/NFL-PlayerStats.jar"]