#Build out jar
FROM maven:3.9.11-eclipse-temurin-25
WORKDIR /app
COPY src /src
COPY pom.xml .
RUN mvn clean package -DskipTests

#Run jar
FROM eclipse-temurin:25-jdk
WORKDIR /app
COPY target/NFL-PlayerStats.jar runnableApp.jar
ENTRYPOINT ["java","-jar","runnableApp.jar"]